routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\KamarController;
use App\Http\Controllers\User\KamarKostController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TempatKostController;
use App\Http\Controllers\User\TempatKostController as TempatKostUser;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// User Route
Route::get('/', function () {
    return view('user.home');
})->name('home');

Route::get('/tempat-kost', [TempatKostUser::class, 'index'])->name('tempat-kost');
Route::get('/tempat-kost-item', [TempatKostUser::class, 'listFilter'])->name('tempat-kost-item');
Route::get('/tempat-kost/view/{id}', [TempatKostUser::class, 'show'])->name('tempat-kost-view');

Route::get('/kamar-kost/{id}', [KamarKostController::class, 'index'])->name('kamar-kost');

Route::get('/tentang', function () {
    return view('user.tentang');
})->name('tentang');

Route::get('/kontak', function () {
    return view('user.kontak');
})->name('kontak');

// Admin & Pemilik Kost Route
Route::prefix('admin')->middleware('auth')->group(function () {

    Route::resource('/', DashboardController::class);
    Route::resource('/tempat', TempatKostController::class);
    Route::resource('/kamar', KamarController::class);


    Route::get('/users', function () {
        // Matches The "/admin/users" URL
    });
});


// ETC Route
Route::get('/demo', function () {
    return view('demo');
});

require __DIR__.'/auth.php';

app/Http/Controllers/Admin/KamarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Fasilitas;
use App\Models\FasilitasKost;
use App\Models\GambarKamar;
use App\Models\KamarKost;
use App\Models\LokasiKost;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class KamarController extends Controller
{
    public function index()
    {

        $fasilitas = null;
        $kamar = KamarKost::with('gambarkamars')->get();

        return view('admin.kamar.index', compact('kamar','fasilitas'));
    }

    public function create()
    {
        $lokasi = LokasiKost::all();
        $kamar = null;
        $type = 1;

        return view('admin.kamar.create', compact('kamar','lokasi','type'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'nama' => 'required',
            'jumlah' => 'required',
            'harga' => 'required',
            'peraturan' => 'required',
            'fasilitas' => 'required',
            'lokasi' => 'required',
        ]);

        $kamar = new KamarKost();
        $kamar->nama = $request->nama;
        $kamar->jumlah = $request->jumlah;
        $kamar->harga = $request->harga;
        $kamar->peraturan = $request->peraturan;
        $kamar->fasilitas = $request->fasilitas;
        $kamar->lokasi_kost_id = $request->lokasi;
        $kamar->save();
        $images = [];

        if(isset($request->file)){
            foreach($request->file as $image){  
                $extension = $image->getClientOriginalExtension();
                $imageName = time().rand(1,99).'.'.$extension;
                $path = $image->storeAs('uploads', $imageName, 'public');
                $images[] = [
                    'path' => $path,
                    'kamar_kost_id' => $kamar->id,
                ];
            }
        }

        foreach ($images as $key => $image) {
            GambarKamar::create($image);
        }

        return redirect()->route('kamar.index')->with('success','Data Telah Disimpan');
    }

    public function show($id)
    {
        $kamar = KamarKost::with('gambarkamars')->find($id);
        $lokasi = LokasiKost::all();

        return view('admin.kamar.create', compact('kamar','lokasi'));
    }

    public function update(Request $request)
    {
        $kamar = KamarKost::with('gambarkamars')->find($request->id);
        $kamar->nama = $request->nama;
        $kamar->jumlah = $request->jumlah;
        $kamar->harga = $request->harga;
        $kamar->peraturan = $request->peraturan;
        $kamar->fasilitas = $request->fasilitas;
        $kamar->lokasi_kost_id = $request->lokasi;
        $kamar->save();

        return redirect()->route('kamar.index')->with('info','Data Telah Diubah');
    }

    public function destroy($id)
    {
        $kamar = KamarKost::with('gambarkamars')->find($id);
        foreach ($kamar->gambarkamars as $key => $value) {
            $delete = Storage::disk('public')->delete($value->path);
        }

        if($delete) {
            $kamar->gambarkamars()->delete();
            $kamar->delete();
        }

        return redirect()->route('kamar.index')->with('error','Data Telah Dihapus');
    }
}

resources/views/admin/kamar/create.blade.php
@extends('admin.layouts.admin')
@section('title')
MimiKost - Tambah Tempat
@endsection
@section('content')
<!-- Sales Overview -->
<div class="card mt-6">

    <!-- header -->
    <div class="card-header flex flex-row justify-between">
        <h1 class="h6">Tambah Tempat Kost</h1>
        <div class="flex flex-row justify-center items-center">

            <a href="{{route('kamar.index')}}" class="btn-bs-primary">
                Back
            </a>
        </div>
    </div>
    <!-- end header -->

    <!-- body -->
    <div class="card-body">
        <div class="w-full max-w-xl">
           <form class="px-8 pt-6 pb-8 mb-6" action="{{isset($kamar) ? route('kamar.update',$kamar->id) : route('kamar.store') }}" method="POST" enctype="multipart/form-data" autocomplete="off">
                {!! csrf_field() !!}
                {!! isset($kamar) ? method_field('PUT'):'' !!}
                <input type="hidden" name="id" value="{{ isset($kamar) ? $kamar->id : '' }}"> <br>
                @if (count($errors) > 0)
                <div class="alert alert-error">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="nama">
                        Nama
                    </label>
                    <input
                        class="shadow border rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline @error('nama') is-invalid @enderror"
                        id="nama" name="nama" type="text" placeholder="Masukkan nama kost" value="{{ isset($kamar) ? $kamar->nama : Request::old('nama') }}">
                    @error('nama')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="lokasi">
                        Lokasi
                    </label>
                    <select name="lokasi" id="lokasi"
                        class="shadow border rounded w-full py-2 px-3 focus:outline-none focus:shadow-outline">
                        @foreach ($lokasi as $item)
                            <option value="{{$item->id}}" {{ (isset($kamar) && $kamar->lokasi_kost_id == $item->id) ? 'selected' : ''}}>{{$item->lokasi_tempat}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="harga">
                        Harga
                    </label>
                    <input
                        class="shadow border rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline @error('harga') is-invalid @enderror"
                        id="harga" name="harga" type="number" placeholder="Massukkan harga" value="{{ isset($kamar) ? $kamar->harga : Request::old('harga') }}">
                    @error('harga')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="jumlah">
                        Jumlah
                    </label>
                    <input
                        class="shadow border rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline @error('jumlah') is-invalid @enderror"
                        id="jumlah" name="jumlah" type="number" placeholder="Massukkan jumlah" value="{{ isset($kamar) ? $kamar->jumlah : Request::old('jumlah') }}">
                    @error('jumlah')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="fasilitas">
                        Fasilitas
                    </label>
                        <input class="mr-1"  type="checkbox" value="Kamar Mandi Dalam" @if ($kamar)   
                            @foreach ($kamar->fasilitas as $item)
                                {{$item == "Kamar Mandi Dalam" ? 'checked' : ''}}
                            @endforeach @endif  name="fasilitas[]" id="fasilitas"> Kamar Mandi Dalam
                        <input class="mr-1"  type="checkbox" value="Kamar Mandi Luar" @if ($kamar)   
                            @foreach ($kamar->fasilitas as $item)
                                {{$item == "Kamar Mandi Luar" ? 'checked' : ''}}
                            @endforeach @endif  name="fasilitas[]" id="fasilitas"> Kamar Mandi Luar
                        <input class="mr-1"  type="checkbox" value="Free Wifi" @if ($kamar)   
                            @foreach ($kamar->fasilitas as $item)
                                {{$item == "Free Wifi" ? 'checked' : ''}}
                            @endforeach @endif  name="fasilitas[]" id="fasilitas"> Free Wifi
                        <input class="mr-1"  type="checkbox" value="Dapur" @if ($kamar)   
                            @foreach ($kamar->fasilitas as $item)
                                {{$item == "Dapur" ? 'checked' : ''}}
                            @endforeach @endif  name="fasilitas[]" id="fasilitas"> Dapur <br>
                        <input class="mr-1"  type="checkbox" value="Kulkas" @if ($kamar)   
                            @foreach ($kamar->fasilitas as $item)
                                {{$item == "Kulkas" ? 'checked' : ''}}
                            @endforeach @endif  name="fasilitas[]" id="fasilitas"> Kulkas
                        <input class="mr-1"  type="checkbox" value="Free Listrik" @if ($kamar)   
                            @foreach ($kamar->fasilitas as $item)
                                {{$item == "Free Listrik" ? 'checked' : ''}}
                            @endforeach @endif  name="fasilitas[]" id="fasilitas"> Free Listrik
                </div>
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="peraturan">
                        Peraturan
                    </label>
                    <textarea name="peraturan" id="peraturan" placeholder="Masukkan Peraturan..."
                        class="shadow border rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline @error('peraturan') is-invalid @enderror"
                        cols="30" rows="10">{{ isset($kamar) ? $kamar->peraturan : Request::old('peraturan') }}</textarea>
                    @error('peraturan')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                @if ($kamar == null)
                    <div class="mb-2">
                        @include('admin.kamar.upload')
                    </div>
                @endif
                <div class="flex items-center justify-between">
                    <button
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                        type="submit">
                        {{isset($kamar) ? 'Update' : 'Create'}}
                    </button>
                </div>
            </form>
            {{-- @if ($kamar)
                <div class="row">
                @foreach ($kamar->gambarkamars as $item)
                    <div class="column">
                        <img src="{{asset('storage/'.$item->path)}}" alt="" style="width: 100%" srcset="">
                    </div>
                @endforeach
                </div>
            @endif --}}
        </div>
    </div>
    <!-- end body -->
</div>
{{-- <style>
    .column {
        float: left;
        width: 33.33%;
        padding: 5px;
    }

    /* Clear floats after image containers */
    .row::after {
        content: "";
        clear: both;
        display: table;
    }
</style> --}}
@endsection

resources/views/admin/kamar/index.blade.php
@extends('admin.layouts.admin')
@section('title')
MimiKost - Kamar Kost
@endsection
@section('content')
<!-- Sales Overview -->
<div class="card mt-6">

    <!-- header -->
    <div class="card-header flex flex-row justify-between">
        <h1 class="h6">Kamar Kost</h1>
        <div class="flex flex-row justify-center items-center">

            <a href="{{route('kamar.create')}}" class="btn-bs-primary">
                Create
            </a>
        </div>
    </div>
    <!-- end header -->

    <!-- body -->
    <div class="card-body">
        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-close mb-5">
                <button class="alert-btn-close">
                    <i class="fad fa-times"></i>
                </button>
                <span>{{ $message }}</span>
            </div>
        @elseif ($message = Session::get('error'))
            <div class="alert alert-error alert-close">
                <button class="alert-btn-close">
                    <i class="fad fa-times"></i>
                </button>
                <span>{{ $message }}</span>
            </div>
        @elseif ($message = Session::get('info'))
            <div class="alert alert-default alert-close mb-5">
                <button class="alert-btn-close">
                    <i class="fad fa-times"></i>
                </button>
                <span>{{ $message }}</span>
            </div>
        @endif
        <table class="w-full">
            <thead>
                <tr>
                    <th class="px-4 py-2">No</th>
                    <th class="px-4 py-2">Nama Kamar</th>
                    <th class="px-4 py-2">Lokasi</th>
                    <th class="px-4 py-2">Jumlah</th>
                    <th class="px-4 py-2">Harga</th>
                    <th class="px-4 py-2">Fasilitas</th>
                    <th class="px-4 py-2">Gambar</th>
                    <th class="px-4 py-2 w-3/12">Aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($kamar as $key => $value)
                    <tr class="hover:bg-gray-200">
                        <td class="border px-4 py-2">{{ $key+1 }}</td>
                        <td class="border px-4 py-2">{{$value->nama}}</td>
                        <td class="border px-4 py-2">{{$value->lokasi->lokasi_tempat}}</td>
                        <td class="border px-4 py-2">{{$value->jumlah}}</td>
                        <td class="border px-4 py-2">Rp.{{number_format($value->harga,2) }}</td>
                        <td class="border px-4 py-2 ">
                            @foreach ($value->fasilitas as $item)
                                <div class="bg-black text-white px-2 py-1 text-sm rounded-full inline-block mb-1">{{$item}}</div>
                            @endforeach
                        </td>
                        <td class="border px-4 py-2">
                            @foreach ($value->gambarkamars as $item)
                                <div class="w-16 h-16 bg-center bg-cover rounded-lg mx-auto" style="background-image: url({{asset('storage/'.$item->path)}})" />
                            @endforeach
                        </td>
                        <td class="border px-4 py-2">
                            <div class="grid grid-cols-2 gap-4">
                                <a href="{{route('kamar.show',$value->id)}}"
                                    class="btn bg-blue-500 hover:bg-blue-700 hover:text-white text-white font-bold py-2 px-4 rounded">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                    </svg>
                                    Update
                                </a>
                                <form action="{{route('kamar.destroy',$value->id)}}" method="POST">
                                    @csrf
                                    @method('delete')
                                    <button onclick="return confirm('Kamar kost juga akan terhapus')"
                                    class="btn bg-red-500 hover:bg-red-700 hover:text-white text-white font-bold py-2 px-4 rounded">
                                         <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block" fill="none" viewBox="0 0 24 24"
                                        stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                        </svg>
                                        Delete
                                    </button>
                                </form>
                                {{-- <a href="#" onclick="return confirm('Kamar kost juga akan terhapus')"
                                    class="btn bg-red-500 hover:bg-red-700 hover:text-white text-white font-bold py-2 px-4 rounded">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                    </svg>
                                    Delete
                                </a> --}}
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>
    <!-- end body -->

</div>
<!-- end Sales Overview -->
@endsection

resources/views/admin/kamar/upload.blade.php
<article aria-label="File Upload Modal" class="relative h-full flex flex-col rounded-md" ondrop="dropHandler(event);" ondragover="dragOverHandler(event);" ondragleave="dragLeaveHandler(event);" ondragenter="dragEnterHandler(event);">
          <!-- overlay -->
          <div id="overlay" class="w-full h-full absolute top-0 left-0 pointer-events-none z-50 flex flex-col items-center justify-center rounded-md">
            <i>
              <svg class="fill-current w-12 h-12 mb-3 text-blue-700" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M19.479 10.092c-.212-3.951-3.473-7.092-7.479-7.092-4.005 0-7.267 3.141-7.479 7.092-2.57.463-4.521 2.706-4.521 5.408 0 3.037 2.463 5.5 5.5 5.5h13c3.037 0 5.5-2.463 5.5-5.5 0-2.702-1.951-4.945-4.521-5.408zm-7.479-1.092l4 4h-3v4h-2v-4h-3l4-4z" />
              </svg>
            </i>
            <p class="text-lg text-blue-700">Drop files to upload</p>
          </div>

          <!-- scroll area -->
          <section class="h-full overflow-auto p-8 w-full h-full flex flex-col">
            <header class="border-dashed border-2 border-gray-400 py-12 flex flex-col justify-center items-center">
              <p class="mb-3 font-semibold text-gray-900 flex flex-wrap justify-center">
                <span>Drag and drop your</span>&nbsp;<span>files anywhere or</span>
              </p>
              <input id="hidden-input" type="file" name="{{$type == 1 ? 'file[]' : 'file'}}" multiple class="hidden" />
              <button id="button" type="button" class="mt-2 rounded-sm px-3 py-1 bg-gray-200 hover:bg-gray-300 focus:shadow-outline focus:outline-none">
                Upload a file
              </button>
            </header>

            <h1 class="pt-8 pb-3 font-semibold sm:text-lg text-gray-900">
              To Upload
            </h1>

            <ul id="gallery" class="flex flex-1 flex-wrap -m-1">
              <li id="empty" class="h-full w-full text-center flex flex-col items-center justify-center items-center">
                <img class="mx-auto w-32" src="https://user-images.githubusercontent.com/507615/54591670-ac0a0180-4a65-11e9-846c-e55ffce0fe7b.png" alt="no data" />
                <span class="text-small text-gray-500">No files selected</span>
              </li>
            </ul>
          </section>
        </article>
      </main>
    </div>

    <!-- using two similar templates for simplicity in js code -->
    <template id="file-template">
      <li class="block p-1 w-1/2 sm:w-1/3 md:w-1/4 lg:w-1/6 xl:w-1/8 h-24">
        <article tabindex="0" class="group w-full h-full rounded-md focus:outline-none focus:shadow-outline elative bg-gray-100 cursor-pointer relative shadow-sm">
          <img alt="upload preview" class="img-preview hidden w-full h-full sticky object-cover rounded-md bg-fixed" />

          <section class="flex flex-col rounded-md text-xs break-words w-full h-full z-20 absolute top-0 py-2 px-3">
            <h1 class="flex-1 group-hover:text-blue-800"></h1>
            <div class="flex">
              <span class="p-1 text-blue-800">
                <i>
                  <svg class="fill-current w-4 h-4 ml-auto pt-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M15 2v5h5v15h-16v-20h11zm1-2h-14v24h20v-18l-6-6z" />
                  </svg>
                </i>
              </span>
              <p class="p-1 size text-xs text-gray-700"></p>
              <button class="delete ml-auto focus:outline-none hover:bg-gray-300 p-1 rounded-md text-gray-800">
                <svg class="pointer-events-none fill-current w-4 h-4 ml-auto" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                  <path class="pointer-events-none" d="M3 6l3 18h12l3-18h-18zm19-4v2h-20v-2h5.711c.9 0 1.631-1.099 1.631-2h5.316c0 .901.73 2 1.631 2h5.711z" />
                </svg>
              </button>
            </div>
          </section>
        </article>
      </li>
    </template>

    <template id="image-template">
      <li class="block p-1 w-1/2 sm:w-1/3 md:w-1/4 lg:w-1/6 xl:w-1/8 h-24">
        <article tabindex="0" class="group hasImage w-full h-full rounded-md focus:outline-none focus:shadow-outline bg-gray-100 cursor-pointer relative text-transparent hover:text-white shadow-sm">
          <img alt="upload preview" class="img-preview w-full h-full sticky object-cover rounded-md bg-fixed" />

          <section class="flex flex-col rounded-md text-xs break-words w-full h-full z-20 absolute top-0 py-2 px-3">
            <h1 class="flex-1"></h1>
            <div class="flex">
              <span class="p-1">
                <i>
                  <svg class="fill-current w-4 h-4 ml-auto pt-" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M5 8.5c0-.828.672-1.5 1.5-1.5s1.5.672 1.5 1.5c0 .829-.672 1.5-1.5 1.5s-1.5-.671-1.5-1.5zm9 .5l-2.519 4-2.481-1.96-4 5.96h14l-5-8zm8-4v14h-20v-14h20zm2-2h-24v18h24v-18z" />
                  </svg>
                </i>
              </span>

              <p class="p-1 size text-xs"></p>
              <button class="delete ml-auto focus:outline-none hover:bg-gray-300 p-1 rounded-md">
                <svg class="pointer-events-none fill-current w-4 h-4 ml-auto" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                  <path class="pointer-events-none" d="M3 6l3 18h12l3-18h-18zm19-4v2h-20v-2h5.711c.9 0 1.631-1.099 1.631-2h5.316c0 .901.73 2 1.631 2h5.711z" />
                </svg>
              </button>
            </div>
          </section>
        </article>
      </li>
    </template>
@section('js-custom')
<!-- end Sales Overview -->
<script>
const fileTempl = document.getElementById("file-template"),
  imageTempl = document.getElementById("image-template"),
  empty = document.getElementById("empty");

// use to store pre selected files
let FILES = {};

// check if file is of type image and prepend the initialied
// template to the target element
function addFile(target, file) {
  const isImage = file.type.match("image.*"),
    objectURL = URL.createObjectURL(file);

  const clone = isImage
    ? imageTempl.content.cloneNode(true)
    : fileTempl.content.cloneNode(true);

  clone.querySelector("h1").textContent = file.name;
  clone.querySelector("li").id = objectURL;
  clone.querySelector(".delete").dataset.target = objectURL;
  clone.querySelector(".size").textContent =
    file.size > 1024
      ? file.size > 1048576
        ? Math.round(file.size / 1048576) + "mb"
        : Math.round(file.size / 1024) + "kb"
      : file.size + "b";

  isImage &&
    Object.assign(clone.querySelector("img"), {
      src: objectURL,
      alt: file.name
    });

  empty.classList.add("hidden");
  target.prepend(clone);

  FILES[objectURL] = file;
}

const gallery = document.getElementById("gallery"),
  overlay = document.getElementById("overlay");

// click the hidden input of type file if the visible button is clicked
// and capture the selected files
const hidden = document.getElementById("hidden-input");
document.getElementById("button").onclick = () => hidden.click();
hidden.onchange = (e) => {
  for (const file of e.target.files) {
    addFile(gallery, file);
  }
};

// use to check if a file is being dragged
const hasFiles = ({ dataTransfer: { types = [] } }) =>
  types.indexOf("Files") > -1;

// use to drag dragenter and dragleave events.
// this is to know if the outermost parent is dragged over
// without issues due to drag events on its children
let counter = 0;

// reset counter and append file to gallery when file is dropped
function dropHandler(ev) {
  ev.preventDefault();
  for (const file of ev.dataTransfer.files) {
    addFile(gallery, file);
    overlay.classList.remove("draggedover");
    counter = 0;
  }
}

// only react to actual files being dragged
function dragEnterHandler(e) {
  e.preventDefault();
  if (!hasFiles(e)) {
    return;
  }
  ++counter && overlay.classList.add("draggedover");
}

function dragLeaveHandler(e) {
  1 > --counter && overlay.classList.remove("draggedover");
}

function dragOverHandler(e) {
  if (hasFiles(e)) {
    e.preventDefault();
  }
}

// event delegation to caputre delete events
// fron the waste buckets in the file preview cards
gallery.onclick = ({ target }) => {
  if (target.classList.contains("delete")) {
    const ou = target.dataset.target;
    document.getElementById(ou).remove(ou);
    gallery.children.length === 1 && empty.classList.remove("hidden");
    delete FILES[ou];
  }
};
</script>

<style>
.hasImage:hover section {
  background-color: rgba(5, 5, 5, 0.4);
}
.hasImage:hover button:hover {
  background: rgba(5, 5, 5, 0.45);
}

#overlay p,
i {
  opacity: 0;
}

#overlay.draggedover {
  background-color: rgba(255, 255, 255, 0.7);
}
#overlay.draggedover p,
#overlay.draggedover i {
  opacity: 1;
}

.group:hover .group-hover\:text-blue-800 {
  color: #2b6cb0;
}
</style>
@endsection